### ISSUE TITLE
Error when configuring SSO

### ISSUE THREAD

**Issue by hffmnn** [org-formation/org-formation-reference#29]
Hi there.

I am trying to follow the step by step instructions in the Readme, but unfortunately, I get an error when trying to configure the groups for SSO:

<img width="559" alt="Screenshot 2021-02-03 at 09 53 02" src="https://user-images.githubusercontent.com/352753/106722198-f2d75500-6605-11eb-99ef-c5f895b7b7a0.png">

Any ideas?

**Comment by eduardomourar** [comment]
I believe we never actually created the groups with those names in AWS SSO. Could you try just with the name `admin`?

**Comment by hffmnn** [comment]
Tried and that works.

 But I thought the setup steps were required before one can start? Or did I misunderstand that?

**Comment by eduardomourar** [comment]
if you have an external IdP, you can just set automatic provisioning during your AWS SSO setup, then all your user and groups would be synced.

**Comment by OlafConijn** [comment]
i changed it in the readme. @eduardomourar should we make a plan on how to test and improve the docs?
