### ISSUE TITLE
SCP template: required key [Content] not found , extraneous key [PolicyDocument] is not permitted.

### ISSUE THREAD

**Issue by BigAl** [org-formation/org-formation-reference#42]
The template here 
https://github.com/org-formation/org-formation-reference/blob/0f1d1020a51416e4d81dd7be7d8166cf78252672/src/templates/010-scps/deny-unsupported-regions.yml#L18

Does not appear to match up with the use of the [Community::Organizations::Policy]( https://github.com/org-formation/aws-resource-providers/tree/master/organizations/policy
)

The following error will be the result

```
ERROR: Resource Scp failed because Properties validation failed for resource Scp with message:
#: required key [Content] not found
#: extraneous key [PolicyDocument] is not permitted.
```

**Comment by OlafConijn** [comment]
are you sure you registered the right version of this type?
in version [community-organizations-policy-0.2.1.zip](https://github.com/org-formation/org-formation-reference/blob/master/src/templates/005-types/_tasks.yml#L30-L37) both PolicyDocument and Content are supported, previously only Content.

**Comment by BigAl** [comment]
You are correct it appears fro some reason I have the _task.yml file for types from a previous commit. Outstide the version of  being `community-organizations-policy-0.1.0.zip` instead or `community-organizations-policy-0.2.1.zip` all the `'` are now `"` which tells me I copied and old version.

My apologies.
